# Generated by Django 6.0.1 on 2026-05-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0008_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
