# Generated by Django 6.0.1 on 2026-05-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0009_alter_userprofile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_token_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
