import React from 'react';
import { motion } from 'framer-motion';
import { Scale, AlertTriangle, BookOpen, ShieldAlert } from 'lucide-react';
import Navbar from '../components/layout/Navbar';
import Footer from '../components/layout/Footer';

const TermsPage = () => {
    return (
        <div className="min-h-screen bg-notion-bg text-notion-text flex flex-col selection:bg-accent-emerald/20 selection:text-accent-emerald">
            <Navbar />

            <main className="flex-1 pt-32 pb-24 max-w-4xl mx-auto px-6">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                    className="mb-12 text-center"
                >
                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-notion-hover border border-notion-border text-xs font-semibold text-accent-emerald mb-4">
                        <Scale className="w-3.5 h-3.5" />
                        <span>Effective: August 2026</span>
                    </div>
                    <h1 className="text-4xl sm:text-5xl font-bold tracking-tight mb-4">Terms of Service</h1>
                    <p className="text-notion-muted text-sm max-w-lg mx-auto">
                        Terms, conditions, and regulatory disclaimers governing the use of Cresta's robo-advisory platform.
                    </p>
                </motion.div>

                <div className="space-y-10 text-sm leading-relaxed text-notion-muted">
                    <section className="p-8 rounded-2xl bg-notion-card border border-amber-500/30 space-y-4">
                        <h2 className="text-xl font-bold text-notion-text flex items-center gap-2">
                            <AlertTriangle className="w-5 h-5 text-amber-500" />
                            1. Regulatory Disclaimer & Advisory Nature
                        </h2>
                        <p>
                            Cresta is an engineering and academic project developed by students at Parul University. 
                            The automated stock recommendations, historical backtests, sentiment analysis scores, and conversational AI insights 
                            generated by Cresta are provided solely for <strong className="text-notion-text">educational, simulation, and informational purposes</strong>.
                        </p>
                        <p>
                            Cresta is not currently registered as an Investment Adviser (RIA) or Research Analyst (RA) with the Securities and Exchange Board of India (SEBI). 
                            Nothing on this platform constitutes a direct solicitation, endorsement, or offer to buy or sell securities.
                        </p>
                    </section>

                    <section className="p-8 rounded-2xl bg-notion-card border border-notion-border space-y-4">
                        <h2 className="text-xl font-bold text-notion-text flex items-center gap-2">
                            <ShieldAlert className="w-5 h-5 text-accent-emerald" />
                            2. Market Risk Acknowledgement
                        </h2>
                        <p>
                            Investments in equity and financial markets are subject to market risks, including the possible loss of principal capital. 
                            Past historical performance evaluated through our backtesting engine does not guarantee future financial returns. 
                            Users are strongly advised to conduct independent due diligence or consult a SEBI-registered financial advisor before committing real capital.
                        </p>
                    </section>

                    <section className="p-8 rounded-2xl bg-notion-card border border-notion-border space-y-4">
                        <h2 className="text-xl font-bold text-notion-text flex items-center gap-2">
                            <BookOpen className="w-5 h-5 text-accent-blue" />
                            3. Algorithmic Processing & Machine Learning Models
                        </h2>
                        <p>
                            Our quantitative algorithms (XGBoost, FinBERT, ARIMA/LSTM ensembles) operate on probabilistic models and historical market data feeds. 
                            While our team strives for high directional accuracy and resilient data sanitation, algorithms may produce errors, anomalies, 
                            or delayed market quotes due to third-party provider latencies.
                        </p>
                    </section>

                    <section className="p-8 rounded-2xl bg-notion-card border border-notion-border space-y-4">
                        <h2 className="text-xl font-bold text-notion-text flex items-center gap-2">
                            <Scale className="w-5 h-5 text-accent-emerald" />
                            4. Intellectual Property
                        </h2>
                        <p>
                            All codebase architectures, custom trained ML weights, design interfaces, and documentation remain the intellectual property 
                            of Ankit Mishra, Om Sharma, Shivam Panchal, and Shubham Jha. The repository is shared under academic open-source guidelines.
                        </p>
                    </section>
                </div>
            </main>

            <Footer />
        </div>
    );
};

export default TermsPage;
